# Generated by Django 5.1.4 on 2025-01-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_edited_messagehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='edited',
        ),
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
