#!/usr/bin/env python3
"""This module defines a function `async_generator`"""
import asyncio
from typing import Generator
import random


async def async_generator() -> Generator[float, None, None]:
    "yields random values generated by the Generator asynchronously"
    for i in range(10):
        await asyncio.sleep(1)
        yield random.uniform(0, 10)
