#!/usr/bin/env python3
"""This module defines a function `async_comprehension`"""
import asyncio
from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """Collects random numbers generated by async_generator()
        using async comprehension
    """
    return [i async for i in async_generator()]
